name: Build and push Docker image
on:
  release:
    types: [published]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:/container"
          file: Containerfile
          push: true
          build-args: |
            IMAGE_VERSION=${{ github.event.release.tag_name }}
          tags: |
            ${{ secrets.DOCKER_USER }}/ark-ascended-server:latest
            ${{ secrets.DOCKER_TOKEN }}/ark-ascended-server-${{ github.event.release.tag_name }}
